--- #YAML:1.0
name:                Regexp-Subst-NoRegex
version:             0.02
abstract:            emulate s/// using s/\Q// or substr
license:             ~
author:              
    - Ben Bullock <ben@nonet>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
